### ISSUE TITLE
please publish to Maven Central

### ISSUE THREAD

**Issue by mvysny** [urosporo/vaadin-quarkus-extension-parent#6]
Hi Michael, I have noticed that the project is linked to JCenter, however it doesn't seem to be published correctly: the "parent" and "deployment" artifacts are missing at https://jcenter.bintray.com/com/urosporo/ , while the project is correctly visible in the private repo at https://dl.bintray.com/mbrem/urosporo/com/urosporo/ .

This forces one to have the private repo in his project, instead of simply depending on JCenter repo only.

**Comment by mvysny** [comment]
Actually the JCenter is being terminated at the end of Feb 2021: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/ , thus it would be great to publish the extension to either Maven Central, or to a github maven repo.

I've found a blog post on how to publish a library onto Maven Central: https://blog.10pines.com/2018/06/25/publish-artifacts-on-maven-central/ (disclaimer - it ain't easy :-p )

**Comment by mbrem** [comment]
The component is released as 1.0.0-rc2 and it's deployed on Maven Central too.
